language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24
    
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - export NDK_VERSION=android-ndk-r11c
    - curl -L https://dl.google.com/android/repository/${NDK_VERSION}-linux-x86_64.zip -O
    - unzip -q ${NDK_VERSION}-linux-x86_64.zip
    - export ANDROID_NDK_HOME=`pwd`/${NDK_VERSION}
    - export PATH=${ANDROID_NDK_HOME}:${PATH}

script: ./install_debug
